/* tslint:disable */
/* eslint-disable */
/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/authentication-api';
export * from './api/history-api';
export * from './api/publishing-api';
export * from './api/push-api';
export * from './api/stats-api';
export * from './api/status-api';

