/* tslint:disable */
/* eslint-disable */
/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Message } from '../models';
// @ts-ignore
import { PresenceMessage } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * HistoryApi - axios parameter creator
 * @export
 */
export const HistoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get message history for a channel
         * @summary Get message history for a channel
         * @param {string} channelId The [Channel\&#39;s ID](https://www.ably.io/documentation/rest/channels).
         * @param {string} [xAblyVersion] The version of the API you wish to use.
         * @param {'json' | 'jsonp' | 'msgpack' | 'html'} [format] The response format you would like
         * @param {string} [start] 
         * @param {number} [limit] 
         * @param {string} [end] 
         * @param {'forwards' | 'backwards'} [direction] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessagesByChannel: async (channelId: string, xAblyVersion?: string, format?: 'json' | 'jsonp' | 'msgpack' | 'html', start?: string, limit?: number, end?: string, direction?: 'forwards' | 'backwards', options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'channelId' is not null or undefined
            assertParamExists('getMessagesByChannel', 'channelId', channelId)
            const localVarPath = `/channels/{channel_id}/messages`
                .replace(`{${"channel_id"}}`, encodeURIComponent(String(channelId !== undefined ? channelId : `-channel_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)
            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = end;
            }

            if (direction !== undefined) {
                localVarQueryParameter['direction'] = direction;
            }

            if (xAblyVersion != null) {
                localVarHeaderParameter['X-Ably-Version'] = String(xAblyVersion);
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/channels/{channel_id}/messages',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get presence on a channel
         * @summary Get presence history of a channel
         * @param {string} channelId The [Channel\&#39;s ID](https://www.ably.io/documentation/rest/channels).
         * @param {string} [xAblyVersion] The version of the API you wish to use.
         * @param {'json' | 'jsonp' | 'msgpack' | 'html'} [format] The response format you would like
         * @param {string} [start] 
         * @param {number} [limit] 
         * @param {string} [end] 
         * @param {'forwards' | 'backwards'} [direction] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresenceHistoryOfChannel: async (channelId: string, xAblyVersion?: string, format?: 'json' | 'jsonp' | 'msgpack' | 'html', start?: string, limit?: number, end?: string, direction?: 'forwards' | 'backwards', options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'channelId' is not null or undefined
            assertParamExists('getPresenceHistoryOfChannel', 'channelId', channelId)
            const localVarPath = `/channels/{channel_id}/presence/history`
                .replace(`{${"channel_id"}}`, encodeURIComponent(String(channelId !== undefined ? channelId : `-channel_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)
            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = end;
            }

            if (direction !== undefined) {
                localVarQueryParameter['direction'] = direction;
            }

            if (xAblyVersion != null) {
                localVarHeaderParameter['X-Ably-Version'] = String(xAblyVersion);
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/channels/{channel_id}/presence/history',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HistoryApi - functional programming interface
 * @export
 */
export const HistoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HistoryApiAxiosParamCreator(configuration)
    return {
        /**
         * Get message history for a channel
         * @summary Get message history for a channel
         * @param {HistoryApiGetMessagesByChannelRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMessagesByChannel(requestParameters: HistoryApiGetMessagesByChannelRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Message>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMessagesByChannel(requestParameters.channelId, requestParameters.xAblyVersion, requestParameters.format, requestParameters.start, requestParameters.limit, requestParameters.end, requestParameters.direction, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get presence on a channel
         * @summary Get presence history of a channel
         * @param {HistoryApiGetPresenceHistoryOfChannelRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPresenceHistoryOfChannel(requestParameters: HistoryApiGetPresenceHistoryOfChannelRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PresenceMessage>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPresenceHistoryOfChannel(requestParameters.channelId, requestParameters.xAblyVersion, requestParameters.format, requestParameters.start, requestParameters.limit, requestParameters.end, requestParameters.direction, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * HistoryApi - factory interface
 * @export
 */
export const HistoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HistoryApiFp(configuration)
    return {
        /**
         * Get message history for a channel
         * @summary Get message history for a channel
         * @param {HistoryApiGetMessagesByChannelRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessagesByChannel(requestParameters: HistoryApiGetMessagesByChannelRequest, options?: AxiosRequestConfig): AxiosPromise<Array<Message>> {
            return localVarFp.getMessagesByChannel(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get presence on a channel
         * @summary Get presence history of a channel
         * @param {HistoryApiGetPresenceHistoryOfChannelRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresenceHistoryOfChannel(requestParameters: HistoryApiGetPresenceHistoryOfChannelRequest, options?: AxiosRequestConfig): AxiosPromise<Array<PresenceMessage>> {
            return localVarFp.getPresenceHistoryOfChannel(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getMessagesByChannel operation in HistoryApi.
 * @export
 * @interface HistoryApiGetMessagesByChannelRequest
 */
export type HistoryApiGetMessagesByChannelRequest = {
    
    /**
    * The [Channel\'s ID](https://www.ably.io/documentation/rest/channels).
    * @type {string}
    * @memberof HistoryApiGetMessagesByChannel
    */
    readonly channelId: string
    
    /**
    * The version of the API you wish to use.
    * @type {string}
    * @memberof HistoryApiGetMessagesByChannel
    */
    readonly xAblyVersion?: string
    
    /**
    * The response format you would like
    * @type {'json' | 'jsonp' | 'msgpack' | 'html'}
    * @memberof HistoryApiGetMessagesByChannel
    */
    readonly format?: 'json' | 'jsonp' | 'msgpack' | 'html'
    
    /**
    * 
    * @type {string}
    * @memberof HistoryApiGetMessagesByChannel
    */
    readonly start?: string
    
    /**
    * 
    * @type {number}
    * @memberof HistoryApiGetMessagesByChannel
    */
    readonly limit?: number
    
    /**
    * 
    * @type {string}
    * @memberof HistoryApiGetMessagesByChannel
    */
    readonly end?: string
    
    /**
    * 
    * @type {'forwards' | 'backwards'}
    * @memberof HistoryApiGetMessagesByChannel
    */
    readonly direction?: 'forwards' | 'backwards'
    
}

/**
 * Request parameters for getPresenceHistoryOfChannel operation in HistoryApi.
 * @export
 * @interface HistoryApiGetPresenceHistoryOfChannelRequest
 */
export type HistoryApiGetPresenceHistoryOfChannelRequest = {
    
    /**
    * The [Channel\'s ID](https://www.ably.io/documentation/rest/channels).
    * @type {string}
    * @memberof HistoryApiGetPresenceHistoryOfChannel
    */
    readonly channelId: string
    
    /**
    * The version of the API you wish to use.
    * @type {string}
    * @memberof HistoryApiGetPresenceHistoryOfChannel
    */
    readonly xAblyVersion?: string
    
    /**
    * The response format you would like
    * @type {'json' | 'jsonp' | 'msgpack' | 'html'}
    * @memberof HistoryApiGetPresenceHistoryOfChannel
    */
    readonly format?: 'json' | 'jsonp' | 'msgpack' | 'html'
    
    /**
    * 
    * @type {string}
    * @memberof HistoryApiGetPresenceHistoryOfChannel
    */
    readonly start?: string
    
    /**
    * 
    * @type {number}
    * @memberof HistoryApiGetPresenceHistoryOfChannel
    */
    readonly limit?: number
    
    /**
    * 
    * @type {string}
    * @memberof HistoryApiGetPresenceHistoryOfChannel
    */
    readonly end?: string
    
    /**
    * 
    * @type {'forwards' | 'backwards'}
    * @memberof HistoryApiGetPresenceHistoryOfChannel
    */
    readonly direction?: 'forwards' | 'backwards'
    
}

/**
 * HistoryApiGenerated - object-oriented interface
 * @export
 * @class HistoryApiGenerated
 * @extends {BaseAPI}
 */
export class HistoryApiGenerated extends BaseAPI {
    /**
     * Get message history for a channel
     * @summary Get message history for a channel
     * @param {HistoryApiGetMessagesByChannelRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistoryApiGenerated
     */
    public getMessagesByChannel(requestParameters: HistoryApiGetMessagesByChannelRequest, options?: AxiosRequestConfig) {
        return HistoryApiFp(this.configuration).getMessagesByChannel(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get presence on a channel
     * @summary Get presence history of a channel
     * @param {HistoryApiGetPresenceHistoryOfChannelRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistoryApiGenerated
     */
    public getPresenceHistoryOfChannel(requestParameters: HistoryApiGetPresenceHistoryOfChannelRequest, options?: AxiosRequestConfig) {
        return HistoryApiFp(this.configuration).getPresenceHistoryOfChannel(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
