/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Occupancy } from './occupancy';

/**
 * A ChannelStatus instance.
 * @export
 * @interface ChannelStatus
 */
export interface ChannelStatus {
    /**
     * A required boolean value indicating whether the channel that is the subject of the event is active. For events indicating regional activity of a channel this indicates activity in that region, not global activity.
     * @type {boolean}
     * @memberof ChannelStatus
     */
    'isActive': boolean;
    /**
     * 
     * @type {Occupancy}
     * @memberof ChannelStatus
     */
    'occupancy'?: Occupancy;
}

