/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChannelStatus } from './channel-status';

/**
 * 
 * @export
 * @interface ChannelDetails
 */
export interface ChannelDetails {
    /**
     * The required name of the channel including any qualifier, if any.
     * @type {string}
     * @memberof ChannelDetails
     */
    'channelId': string;
    /**
     * In events relating to the activity of a channel in a specific region, this optionally identifies whether or not that region is responsible for global coordination of the channel.
     * @type {boolean}
     * @memberof ChannelDetails
     */
    'isGlobalMaster'?: boolean;
    /**
     * In events relating to the activity of a channel in a specific region, this optionally identifies the region.
     * @type {string}
     * @memberof ChannelDetails
     */
    'region'?: string;
    /**
     * 
     * @type {ChannelStatus}
     * @memberof ChannelDetails
     */
    'status'?: ChannelStatus;
}

