/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Recipient } from './recipient';

/**
 * 
 * @export
 * @interface DeviceDetails
 */
export interface DeviceDetails {
    /**
     * Optional trusted client identifier for the device.
     * @type {string}
     * @memberof DeviceDetails
     */
    'clientId'?: string;
    /**
     * Secret value for the device.
     * @type {string}
     * @memberof DeviceDetails
     */
    'deviceSecret'?: string;
    /**
     * Form factor of the push device.
     * @type {string}
     * @memberof DeviceDetails
     */
    'formFactor'?: DeviceDetailsFormFactorEnum;
    /**
     * Unique identifier for the device generated by the device itself.
     * @type {string}
     * @memberof DeviceDetails
     */
    'id'?: string;
    /**
     * Optional metadata object for this device. The metadata for a device may only be set by clients with push-admin privileges and will be used more extensively in the future with smart notifications.
     * @type {object}
     * @memberof DeviceDetails
     */
    'metadata'?: object;
    /**
     * Platform of the push device.
     * @type {string}
     * @memberof DeviceDetails
     */
    'platform'?: DeviceDetailsPlatformEnum;
    /**
     * 
     * @type {Recipient}
     * @memberof DeviceDetails
     */
    'push.recipient'?: Recipient;
    /**
     * the current state of the push device.
     * @type {string}
     * @memberof DeviceDetails
     */
    'push.state'?: DeviceDetailsPushStateEnum;
}

type DeviceDetailsFormFactorEnum = 'phone' | 'tablet' | 'desktop' | 'tv' | 'watch' | 'car' | 'embedded'
type DeviceDetailsPlatformEnum = 'ios' | 'android'
type DeviceDetailsPushStateEnum = 'Active' | 'Failing' | 'Failed'


