/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Push } from './push';

/**
 * Extras object. Currently only allows for [push](https://www.ably.io/documentation/general/push/publish#channel-broadcast-example) extra.
 * @export
 * @interface Extras
 */
export interface Extras {
    /**
     * 
     * @type {Push}
     * @memberof Extras
     */
    'push'?: Push;
}

