/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChannelDetails } from './channel-details';

/**
 * @type GetMetadataOfAllChannels2XXResponse
 * @export
 */
export type GetMetadataOfAllChannels2XXResponse = Array<ChannelDetails> | Array<string>;


