/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Returned error from failed REST.
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * Error code.
     * @type {number}
     * @memberof ModelError
     */
    'code'?: number;
    /**
     * Link to help with error.
     * @type {string}
     * @memberof ModelError
     */
    'href'?: string;
    /**
     * Message explaining the error\'s cause.
     * @type {string}
     * @memberof ModelError
     */
    'message'?: string;
    /**
     * Server ID with which error was encountered.
     * @type {string}
     * @memberof ModelError
     */
    'serverId'?: string;
    /**
     * Status error code.
     * @type {number}
     * @memberof ModelError
     */
    'statusCode'?: number;
}

