/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * Text below title on the expanded notification.
     * @type {string}
     * @memberof Notification
     */
    'body'?: string;
    /**
     * Platform-specific, used to group notifications together.
     * @type {string}
     * @memberof Notification
     */
    'collapseKey'?: string;
    /**
     * Platform-specific icon for the notification.
     * @type {string}
     * @memberof Notification
     */
    'icon'?: string;
    /**
     * Platform-specific sound for the notification.
     * @type {string}
     * @memberof Notification
     */
    'sound'?: string;
    /**
     * Title to display at the notification.
     * @type {string}
     * @memberof Notification
     */
    'title'?: string;
}

