/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An Occupancy instance indicating the occupancy of a channel. For events indicating regional activity of a channel this indicates activity in that region, not global activity.
 * @export
 * @interface Occupancy
 */
export interface Occupancy {
    /**
     * The number of connections that are authorised to enter members into the presence channel.
     * @type {number}
     * @memberof Occupancy
     */
    'presenceConnections'?: number;
    /**
     * The number of members currently entered into the presence channel.
     * @type {number}
     * @memberof Occupancy
     */
    'presenceMembers'?: number;
    /**
     * The number of connections that are authorised to subscribe to presence messages.
     * @type {number}
     * @memberof Occupancy
     */
    'presenceSubscribers'?: number;
    /**
     * The number of connections attached to the channel that are authorised to publish.
     * @type {number}
     * @memberof Occupancy
     */
    'publishers'?: number;
    /**
     * The number of connections attached that are authorised to subscribe to messages.
     * @type {number}
     * @memberof Occupancy
     */
    'subscribers'?: number;
}

