/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Extras } from './extras';

/**
 * 
 * @export
 * @interface PresenceMessage
 */
export interface PresenceMessage {
    /**
     * The event signified by a PresenceMessage.
     * @type {string}
     * @memberof PresenceMessage
     */
    'action'?: PresenceMessageActionEnum;
    /**
     * The client ID of the publisher of this presence update.
     * @type {string}
     * @memberof PresenceMessage
     */
    'clientId'?: string;
    /**
     * The connection ID of the publisher of this presence update.
     * @type {string}
     * @memberof PresenceMessage
     */
    'connectionId'?: string;
    /**
     * The presence update payload, if provided.
     * @type {string}
     * @memberof PresenceMessage
     */
    'data'?: string;
    /**
     * This will typically be empty as all presence updates received from Ably are automatically decoded client-side using this value. However, if the message encoding cannot be processed, this attribute will contain the remaining transformations not applied to the data payload.
     * @type {string}
     * @memberof PresenceMessage
     */
    'encoding'?: string;
    /**
     * 
     * @type {Extras}
     * @memberof PresenceMessage
     */
    'extras'?: Extras;
    /**
     * Unique ID assigned by Ably to this presence update.
     * @type {string}
     * @memberof PresenceMessage
     */
    'id'?: string;
    /**
     * Timestamp when the presence update was received by Ably, as milliseconds since the epoch.
     * @type {number}
     * @memberof PresenceMessage
     */
    'timestamp'?: number;
}

type PresenceMessageActionEnum = 'ABSENT' | 'PRESENT' | 'ENTER' | 'LEAVE' | 'UPDATE'


