/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PublishMessagesToChannel2XXResponse
 */
export interface PublishMessagesToChannel2XXResponse {
    /**
     * 
     * @type {string}
     * @memberof PublishMessagesToChannel2XXResponse
     */
    'channel'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublishMessagesToChannel2XXResponse
     */
    'messageId'?: string;
}

