/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Push } from './push';
import { Recipient } from './recipient';

/**
 * 
 * @export
 * @interface PublishPushNotificationToDevicesRequest
 */
export interface PublishPushNotificationToDevicesRequest {
    /**
     * 
     * @type {Push}
     * @memberof PublishPushNotificationToDevicesRequest
     */
    'push'?: Push;
    /**
     * 
     * @type {Recipient}
     * @memberof PublishPushNotificationToDevicesRequest
     */
    'recipient': Recipient;
}

