/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Notification } from './notification';

/**
 * Extends and overrides generic values when delivering via GCM/FCM. [See examples](https://www.ably.io/documentation/general/push/publish#payload-structure)
 * @export
 * @interface PushFcm
 */
export interface PushFcm {
    /**
     * 
     * @type {Notification}
     * @memberof PushFcm
     */
    'notification'?: Notification;
}

