/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Notification } from './notification';
import { PushApns } from './push-apns';
import { PushFcm } from './push-fcm';
import { PushWeb } from './push-web';

/**
 * 
 * @export
 * @interface Push
 */
export interface Push {
    /**
     * 
     * @type {PushApns}
     * @memberof Push
     */
    'apns'?: PushApns;
    /**
     * Arbitrary [key-value string-to-string payload](https://www.ably.io/documentation/general/push/publish#channel-broadcast-example).
     * @type {string}
     * @memberof Push
     */
    'data'?: string;
    /**
     * 
     * @type {PushFcm}
     * @memberof Push
     */
    'fcm'?: PushFcm;
    /**
     * 
     * @type {Notification}
     * @memberof Push
     */
    'notification'?: Notification;
    /**
     * 
     * @type {PushWeb}
     * @memberof Push
     */
    'web'?: PushWeb;
}

