/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Push recipient details for a device.
 * @export
 * @interface Recipient
 */
export interface Recipient {
    /**
     * Client ID of recipient
     * @type {string}
     * @memberof Recipient
     */
    'clientId'?: string;
    /**
     * Client ID of recipient
     * @type {string}
     * @memberof Recipient
     */
    'deviceId'?: string;
    /**
     * when using APNs, specifies the required device token.
     * @type {string}
     * @memberof Recipient
     */
    'deviceToken'?: string;
    /**
     * when using GCM or FCM, specifies the required registration token.
     * @type {string}
     * @memberof Recipient
     */
    'registrationToken'?: string;
    /**
     * Defines which push platform is being used.
     * @type {string}
     * @memberof Recipient
     */
    'transportType'?: RecipientTransportTypeEnum;
}

type RecipientTransportTypeEnum = 'apns' | 'fcm' | 'gcm'


