/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SignedTokenRequestAllOf
 */
export interface SignedTokenRequestAllOf {
    /**
     * A signature, generated as an HMAC of each of the above components, using the key secret value.
     * @type {string}
     * @memberof SignedTokenRequestAllOf
     */
    'mac': string;
}

