/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SubscribePushDeviceToChannelRequestOneOf } from './subscribe-push-device-to-channel-request-one-of';
import { SubscribePushDeviceToChannelRequestOneOf1 } from './subscribe-push-device-to-channel-request-one-of1';

/**
 * @type SubscribePushDeviceToChannelRequest
 * @export
 */
export type SubscribePushDeviceToChannelRequest = SubscribePushDeviceToChannelRequestOneOf | SubscribePushDeviceToChannelRequestOneOf1;


