/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SubscribePushDeviceToChannelRequestOneOf1
 */
export interface SubscribePushDeviceToChannelRequestOneOf1 {
    /**
     * Channel name.
     * @type {string}
     * @memberof SubscribePushDeviceToChannelRequestOneOf1
     */
    'channel'?: string;
    /**
     * Must be set when deviceId is empty, cannot be used with deviceId.
     * @type {string}
     * @memberof SubscribePushDeviceToChannelRequestOneOf1
     */
    'clientId'?: string;
}

