/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TokenRequest
 */
export interface TokenRequest {
    /**
     * The [capabilities](https://www.ably.io/documentation/core-features/authentication#capabilities-explained) (i.e. a set of channel names/namespaces and, for each, a set of operations) which should be a subset of the set of capabilities associated with the key specified in keyName.
     * @type {object}
     * @memberof TokenRequest
     */
    'capability': object;
    /**
     * The [client ID](https://www.ably.io/documentation/core-features/authentication#identified-clients) to be assosciated with the token. Can be set to * to allow for any client ID to be used.
     * @type {string}
     * @memberof TokenRequest
     */
    'clientId'?: string;
    /**
     * Name of the key used for the TokenRequest. The keyName comprises of the app ID and key ID on an API Key.
     * @type {string}
     * @memberof TokenRequest
     */
    'keyName': string;
    /**
     * An unquoted, un-escaped random string of at least 16 characters. Used to ensure the Ably TokenRequest cannot be reused.
     * @type {string}
     * @memberof TokenRequest
     */
    'nonce': string;
    /**
     * Time of creation of the Ably TokenRequest.
     * @type {number}
     * @memberof TokenRequest
     */
    'timestamp': number;
}

