/*
Platform API

The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

The version of the OpenAPI document: 1.1.0
Contact: support@ably.io

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TokenDetails
 */
export interface TokenDetails {
    /**
     * Regular expression representation of the capabilities of the token.
     * @type {string}
     * @memberof TokenDetails
     */
    'capability'?: string;
    /**
     * Timestamp of token expiration.
     * @type {number}
     * @memberof TokenDetails
     */
    'expires'?: number;
    /**
     * Timestamp of token creation.
     * @type {number}
     * @memberof TokenDetails
     */
    'issued'?: number;
    /**
     * Name of the key used to create the token
     * @type {string}
     * @memberof TokenDetails
     */
    'keyName'?: string;
    /**
     * The Ably Token.
     * @type {string}
     * @memberof TokenDetails
     */
    'token'?: string;
}

